### ISSUE TITLE
Tag inference not working

### ISSUE THREAD

**Issue by david-waterworth** [BrickSchema/py-brickschema#32]
I have a simple example file that validates correctly (see attached instances.ttl).

I'm trying to run `SELECT * WHERE { ?x brick:hasTag ?y }`, this works in stardog studio with reasoning enabled (although it also returns (brick:Steam,tag:Gas) , (brick:Steam,tag:Steam) which isn't ideal.

It's not working using the `py-brickschema` reasoners though. For example

```
g = Graph(load_brick=True)
g.load_file("instances.ttl")
g = BrickInferenceSession().expand(g)
print([t for t in g.query("SELECT * WHERE { ?x brick:hasTag ?y }")])
```

returns a single result `[(brick:hasTag,brick:hasTag)]`

In fact, I noticed that the reasoner appears to be inserting triples (?x, ?x, ?x) for every entity in the schema which explains why the above was returned.

This code works (slowly) though

```
g = Graph(load_brick=True)
g.load_file("instances.ttl")
owlrl.DeductiveClosure(owlrl.OWLRL_Semantics).expand(g.g)

print([t for t in g.g.query("SELECT * WHERE { ?x brick:hasTag ?y }")])
```

Maybe I'm using the wrong *InferenceSession?

**Comment by gtfierro** [comment]
Hey there! I'm not seeing an attached `instances.ttl`; could you maybe post it in a gist (or email to me directly).

The BrickInferenceSession is the correct one to use, but it will attempt to use a faster inferencer if one is available. Did you install the `reasonable` or `allegro` variations of BrickSchema? If you uninstall `reasonable` and `docker` in your local virtual environment, then BrickInferenceSession should default to the OWLRL reasoner.

(You may also want to update `reasonable` --- I still have a few bugs to fix but if you are on an older version then some of the more egregious ones like the one you mentioned might have been fixed)

**Comment by david-waterworth** [comment]
I'm using the latest version of reasonable from pypi (installed via `pip install brickschema[reasonable]`). The version is `0.1.12`

I'll have another attempt to upload instances.ttl - if not the contents are:

> @prefix : <https://example.org/ontologies/test#> .
> @prefix brick: <https://brickschema.org/schema/1.1/Brick#> .
> @prefix owl: <http://www.w3.org/2002/07/owl#> .
> 
> :CH1_Active_Power_Sensor a owl:NamedIndividual,
>     brick:Active_Power_Sensor ;
>     brick:isPointOf :CH1 .
> 
> :CH1_Entering_Water_Temperature_Sensor a owl:NamedIndividual,
>     brick:Entering_Water_Temperature_Sensor ;
>     brick:isPointOf :CH1 .
> 
> :CH1_Leaving_Water_Temperature_Sensor a owl:NamedIndividual,
>     brick:Leaving_Water_Temperature_Sensor ;
>     brick:isPointOf :CH1 .
> 
> :CH2_Active_Power_Sensor a owl:NamedIndividual,
>     brick:Active_Power_Sensor ;
>     brick:isPointOf :CH2 .
> 
> :CH2_Leaving_Water_Temperature_Sensor a owl:NamedIndividual,
>     brick:Leaving_Water_Temperature_Sensor ;
>     brick:isPointOf :CH2 .
> 
> :CH3_Entering_Water_Temperature_Sensor a owl:NamedIndividual,
>     brick:Entering_Water_Temperature_Sensor ;
>     brick:isPointOf :CH3 .
> 
> :CH3_Leaving_Water_Temperature_Sensor a owl:NamedIndividual,
>     brick:Leaving_Water_Temperature_Sensor ;
>     brick:isPointOf :CH3 .
> 
> :CH1 a owl:NamedIndividual, brick:Chiller ;
>     brick:hasPoint :CH1_Active_Power_Sensor ;
>     brick:hasPoint :CH1_Entering_Water_Temperature_Sensor ;
>     brick:hasPoint :CH1_Leaving_Water_Temperature_Sensor .
> 
> :CH2 a owl:NamedIndividual, brick:Chiller ;
>     brick:hasPoint :CH2_Active_Power_Sensor ;
>     brick:hasPoint :CH2_Leaving_Water_Temperature_Sensor .
> 
> :CH3 a owl:NamedIndividual, brick:Chiller ;
>     brick:hasPoint :CH3_Entering_Water_Temperature_Sensor ;
>     brick:hasPoint :CH3_Leaving_Water_Temperature_Sensor .

[instances.ttl.zip](https://github.com/BrickSchema/py-brickschema/files/5612889/instances.ttl.zip)

**Comment by gtfierro** [comment]
If the latest version of `reasonable` is causing issues, I will be sure to take a look. If you want a faster reasoner than the default OWLRL, then you can uninstall `reasonable` and install `docker` and that should use the Allegrograph reasoner on the backend.


```
# alternative way of getting the Allegograph reasoner
pip uninstall brickschema
pip install brickschema[allegro]
```

**Comment by david-waterworth** [comment]
I've not had time to get to the bottom of it, but I also noticed that I was getting different results from the Validator between these two usages:

```
validator = Validator()
result = validator.validate(data_graph)
```

and

```
validator = Validator(useBrickSchema=False, useDefaultShapes=False)
result = validator.validate(data_graph, shacl_graphs=[shacl_graph], ont_graphs=[ont_graph])
```

In the second case I loaded the ttl files from disk i..e

```
data_graph = Graph().parse("data.ttl", format="ttl")
shacl_graph = Graph().parse("BrickShape.ttl", format="ttl")
ont_graph = Graph().parse("Brick.ttl", format="ttl")
```

In the first case pyshacl.validate() returns false (it then takes a very long time to build the violation list - way longer than the actual validation). In the second it's valid.

The only difference I can see is the deletion of the rdfs:domain and rdfs:range triples but I manually did that as well and it made no different. I used the BrickShape.ttl from the python package, but Brick.ttl from the brick website - I wonder if they're different? I'll look closer when I get a chance.

**Comment by gtfierro** [comment]
@david-waterworth to your first question, uninstalling `reasonable` and using the `allegro` reasoner seems to fix the issue:

```python
g = brickschema.graph.Graph(load_brick=True)
g.load_file("instances.ttl")
g = brickschema.inference.BrickInferenceSession().expand(g)
print(len([t for t in g.query("SELECT * WHERE { ?x brick:hasTag ?y }")]))
```

gives

```
2020-12-01:17:57:54,769 WARNING [inference.py:125] Reasonable not installed; trying Allegro
Checking 6 containers
Non-zero exit code 1 with message b'\nAllegroGraph Server Edition 7.0.0, built on April 28, 2020 14:19:15 GMT-0700\nCopyright (c) 2005-2020 Franz Inc.  All Rights Reserved.\nAllegroGraph contains patented and patent-pending technologies.\n\nCurrent time: Wednesday, December 02, 2020 01:57:59 AM GMT\n\nDaemonizing...\nWhile: Starting AllegroGraph\n\n  Starting server failed:    There appears to already be an AllegroGraph server running (pid 58).  If it is your intention to run another AllegroGraph server  simultaneously,  please make a separate configuration file which has different values  for the following parameters:    Port               10035  SettingsDirectory  /agraph/data/settings/\n'
204
```

so I'm getting 204 tags back. I'll take a look at `reasonable` in the coming days.

I will also take a look at what's going on with the validation. The packaged versions of Brick and BrickShape that are provided with the `brickschema` install will trail the "nightly" versions provided on the GitHub release, but they shouldn't be substantially different.

**Comment by gtfierro** [comment]
@david-waterworth I have fixed some issues with `reasonable`. If you update to version `0.1.23`, you should be getting correct results now
