### ISSUE TITLE
brickschema v0.3.0 ~ graph.expand("tag") --> Invalid profile: 'tag'

### ISSUE THREAD

**Issue by iamliamc** [BrickSchema/py-brickschema#43]
Hey @gtfierro , 

Just upgraded my local brickschema package from 0.2.5 to 0.3.0 and now I can't validate with tags... 
`graph.expand(profile="tag")  # infers Brick classes from Brick tags`

Am I missing something? 

```
Traceback (most recent call last):
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liam/spectral/spectral_brick/spectral_brick/__main__.py", line 78, in <module>
    g = load_validate_seeded_graph(adapters=adapters, logger=logger, settings=settings)
  File "/home/liam/spectral/spectral_brick/spectral_brick/__main__.py", line 55, in load_validate_seeded_graph
    graph.expand(profile="tag")  # infers Brick classes from Brick tags
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/brickschema/graph.py", line 225, in expand
    raise Exception(f"Invalid profile '{profile}'")
Exception: Invalid profile 'tag'
```

**Comment by iamliamc** [comment]
Looks like 'tag' might have been depricated for 'shacl'? 

```
    def expand(self, profile=None, backend=None):
        """
        Expands the current graph with the inferred triples under the given entailment regime
        and with the given backend. Possible profiles are:
        - 'rdfs': runs RDFS rules
        - 'owlrl': runs full OWLRL reasoning
        - 'vbis': adds VBIS tags
        - 'shacl': does SHACL-AF reasoning (including tag inference, if the extension is loaded)
        ```

**Comment by gtfierro** [comment]
Yes, sorry! I thought it was safe to switch that out :). What is the feature you're trying to use? Adding tags to Brick entities based on which class they are, or going from tags to Brick classes?

If it's the former, you can just use the `"owlrl"` argument to `.expand()`. If it's the latter, then you'll want

```python
g.load_extension("shacl_tag_inference")
g.expand("shacl")
```

**Comment by iamliamc** [comment]
Yeah I'm not exactly sure which hah! 

All i know is that after going to 0.3.0 some of my queries stopped working: 

```
SELECT ?s ?o ?uuid WHERE {
  VALUES ?subclass_constraint { brick:Reset_Setpoint brick:Limit }
  ?s a brick:HeatingCurve .
  ?s brick:hasPoint ?o .
  ?o rdf:type/rdfs:subClassOf* ?subclass_constraint .
  ?o brick:TimeseriesUUID ?uuid .
}
```

```
SELECT DISTINCT ?v ?uuid WHERE {
  VALUES ?types { brick:Heating_Valve brick:Cooling_Valve }
    ?v rdf:type* ?v_types .
  	?v brick:feeds ?o .
  	?o a brick:FCU .
  	?v brick:TimeseriesUUID ?uuid .
  }
```

Let me load that tag inference I bet that is it...

**Comment by iamliamc** [comment]
Hmm so with 0.3.0: 

```
    # perform reasoning on the graph (edits in-place)
    graph.expand(profile="owlrl")

    graph.load_extension("shacl_tag_inference")
    graph.expand("shacl")
```

I get nothing: 
![image](https://user-images.githubusercontent.com/5678517/108784197-d95a6680-753c-11eb-8fe5-432015c96f02.png)

And with 0.2.5 and: 
```
    # perform reasoning on the graph (edits in-place)
    graph.expand(profile="owlrl")
    graph.expand(profile="tag")  # infers Brick classes from Brick tags
```


![image](https://user-images.githubusercontent.com/5678517/108784341-30603b80-753d-11eb-8a4e-0c124d8ebf72.png)

**Comment by gtfierro** [comment]
Make sure your model and query are using the **new** Brick namespace: `https://brickschema.org/schema/Brick#`. My guess is that's whats tripping up your queries.

The intent with moving to the new namespace is *from now on* people won't have to change their models every time we update Brick

**Comment by iamliamc** [comment]
Ohhh ok I was just seeing this looked funny: 
`@prefix brick1: <https://brickschema.org/schema/1.2/Brick#> .`

**Comment by iamliamc** [comment]
Well maybe there is something in the ontology that changed that I was misusing... 

`brickschema==0.3.0`

My ttl file leads with: 
`@prefix brick: <https://brickschema.org/schema/Brick#> .`

```
    # perform reasoning on the graph (edits in-place)
    graph.expand(profile="owlrl")

    graph.load_extension("shacl_tag_inference")
    graph.expand("shacl")
```

It looks like my subclass_constraint is the culprit because when I comment that out I get results (just missing the constraint)... so perhaps something happened in v1.2 related to `brick:Reset_Setpoint` or `brick:Limit`

That I need to handle... 

```
SELECT ?s ?o ?uuid WHERE {
  VALUES ?subclass_constraint { brick:Reset_Setpoint brick:Limit }
  ?s a brick:HeatingCurve .
  ?s brick:hasPoint ?o .
#  ?o rdf:type/rdfs:subClassOf* ?subclass_constraint .
  ?o brick:TimeseriesUUID ?uuid .
}
```
Now there are calculated setpoints etc well duh cause I removed the subclass_constraint. 
![image](https://user-images.githubusercontent.com/5678517/108785685-eaf13d80-753f-11eb-97d5-094361b5b300.png)

**Comment by gtfierro** [comment]
Those classes still exist in v1.2, so that shouldn't be the issue.

Can you verify that you are loading into your graph the correct Brick.ttl file?

Also try replacing your query line `#  ?o rdf:type/rdfs:subClassOf* ?subclass_constraint .` with `?o rdf:type ?subclass_constraint`

From the looks of it, you shouldn't need to include the SHACL/tag stuff

**Comment by iamliamc** [comment]
Yeah confirmed it's the right .ttl (its the only one... gets deleted and regenerated every time I run my code right now). 

Switching to: 
`?o rdf:type ?subclass_constraint`

No change... no results with the statement in place... 
```
SELECT ?s ?o ?uuid WHERE {
  VALUES ?subclass_constraint { brick:Reset_Setpoint brick:Limit }
  ?s a brick:HeatingCurve .
  ?s brick:hasPoint ?o .
  ?o rdf:type ?subclass_constraint .
  ?o brick:TimeseriesUUID ?uuid .
}
```

Get results without it but including types that I don't want: 
```
SELECT ?s ?o ?uuid WHERE {
  VALUES ?subclass_constraint { brick:Reset_Setpoint brick:Limit }
  ?s a brick:HeatingCurve .
  ?s brick:hasPoint ?o .
  #?o rdf:type ?subclass_constraint .
  ?o brick:TimeseriesUUID ?uuid .
}

Tried it with and without the SHACL/tag stuff... 


I'll stick with 0.2.5 for now, and try a couple other things with fresh eyes this week.

**Comment by gtfierro** [comment]
You are generating the Brick.ttl file each time you run your code? Are you doing this from the latest version of the Brick source code? You may need to merge in the latest from Brick `master` to ensure you are generating the correct URI.

If you'd like to go over this on Wednesday (it'll be another office hours meeting --- likely to permanently convert to that in light of the pending working groups) that is an option too

**Comment by iamliamc** [comment]
Ah no I'm generating my building's  .ttl file not the Brick.ttl every time... I thought py brickschema updating to `0.3.0` would control which version of Brick.ttl gets loaded in... `g = brickschema.Graph(load_brick=False)` maybe I just need to run that as True once... 

Sure be great to over where i'm at Wednesday

**Comment by gtfierro** [comment]
If you don't do `load_brick=True`, then it won't load a recent version of Brick into the graph. Without Brick being in your building graph, you can't run queries that involve the subclass relationships (among others) because the subclass relationships are written down in Brick, not your building model.

Try running it with `load_brick=True` and I think that should address the issue you're seeing. I'm curious why it was "working" before...

**Comment by iamliamc** [comment]
I ran it that way once yeah -- great thanks for the back and forth!

**Comment by iamliamc** [comment]
So yes when I use `g = brickschema.Graph(load_brick=True)` with 0.3.0 my query does work (and the entire Brick.ttl ends up embedded in my "working" ttl file when I serialize)... 

Still don't understand with 0.2.5 and `g = brickschema.Graph(load_brick=False)` it works something to explore Wednesday!

**Comment by iamliamc** [comment]
Think I figured it out... 

This namespace actually hosts and serves the Brick.ttl... so in my `0.2.5` version it was getting added "for free": 
`Namespace("https://brickschema.org/schema/1.1/Brick#")` 

![image](https://user-images.githubusercontent.com/5678517/108843951-6affbd80-75a9-11eb-9e47-5f7da2a68f7b.png)


When I switch to `0.3.0` I changed my namespace to which is a 404 I need `load_brick=True`: 
`Namespace("https://brickschema.org/schema/Brick#"

![image](https://user-images.githubusercontent.com/5678517/108844022-836fd800-75a9-11eb-974f-80652d8fc5e0.png)

It was really convienient to not end up having the whole Brick file in my "working ttl file"...

**Comment by iamliamc** [comment]
So the question for me now is how to keep the nice `queries that involve the subclass relationships` while keeping the whole Brick.ttl file from getting stuffed into my working TTL... but this is all "nice to have".

**Comment by gtfierro** [comment]
The new Brick URI should resolve now and not give you a 404.

The semantics of how Brick gets loaded in should not have changed between the two releases. It may be that rdflib was downloading the Brick model in the background, but I don't believe it does that unless there is an `owl:imports` property in the graph. Before, did you notice if your graph actually had the Brick definition triples loaded into it?

You can always keep your building model TTL separate from Brick, but when you want to use them in a program you will have to load both the Brick and the building TTL files into the same in-memory object

**Comment by iamliamc** [comment]
Before using Brick 1.1 and brickschema 0.2.5 it did not have the Brick definition triples loaded in... 

with load_brick=False
```
        brick = Namespace("https://brickschema.org/schema/1.1/Brick#")
        self.graph.bind("brick", brick)
```

I think that 0.3.0 binds brick to the prefix "brick" so when I try to bind as the above (was hoping to keep the whole Brick.ttl out of my building model ttl) I get: 

`@prefix brick1: <https://brickschema.org/schema/1.2/Brick#> .`

Feel like we should be able to get to the bottom of this pretty quick in tomorrow's working group
