### ISSUE TITLE
Consider supporting rdflib_sqlalchemy? 

### ISSUE THREAD

**Issue by iamliamc** [BrickSchema/py-brickschema#45]
Hey @gtfierro 

I finally found what I've been looking for almost right under my nose... 

```
from rdflib import plugin, RDF, Namespace
from rdflib.graph import Graph
from rdflib.store import Store
from rdflib_sqlalchemy import registerplugins

from brickschema import Graph as bGraph

registerplugins()

SQLALCHEMY_URL ="postgresql+psycopg2://liam:pw@localhost:5432/spectral_brick"

store = plugin.get("SQLAlchemy", Store)(identifier="my_store")
graph = Graph(store, identifier="my_graph")
graph.open(SQLALCHEMY_URL, create=True)
BRICK = Namespace("https://brickschema.org/schema/1.2/Brick#")
graph.bind("brick", BRICK)
BLDG = Namespace("https://topology.sbp.spectral.energy/test#")
graph.add((BLDG.Building, RDF.type, BRICK.Building))

result = graph.query("select * where {?s ?p ?o} limit 10")

for subject, predicate, object_ in result:
    print(subject, predicate, object_)

graph.close()
```

When I run this setup with brickschema Graph object I get:
```
Traceback (most recent call last):
  File "test_rdflib_psql.py", line 13, in <module>
    graph = bGraph(store, identifier="my_graph")
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/brickschema/graph.py", line 38, in __init__
    ns.bind_prefixes(self)
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/brickschema/namespaces.py", line 24, in bind_prefixes
    graph.bind("rdf", RDF)
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib/graph.py", line 932, in bind
    return self.namespace_manager.bind(
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib/graph.py", line 326, in _get_namespace_manager
    self.__namespace_manager = NamespaceManager(self)
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib/namespace.py", line 363, in __init__
    for p, n in self.namespaces():  # self.bind is not always called
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib/namespace.py", line 570, in namespaces
    for prefix, namespace in self.store.namespaces():
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib_sqlalchemy/store.py", line 675, in namespaces
    with self.engine.connect() as connection:
AttributeError: 'NoneType' object has no attribute 'connect'

```

**Comment by gtfierro** [comment]
Hmm... my guess is that the plugin is not expecting any additional initialization of the graph (like binding namespaces) to happen until *after* the `.open()` call is made. I took a few minutes to play around with how to approach it and the best solution that is occurring to me --- that doesn't require breaking existing `brickschema` code --- is to have a custom constructor for `brickschema.Graph` that does the SQLAlchemy initialization + `.open()` *before* it attempts to bind the namespaces. Not sure when I"ll have the time to get around to it, but the implementation shouldn't be too difficult to wrangle --- I'm happy to review any stab you want to take at it!

**Comment by iamliamc** [comment]
For now I have just bypassed `pybrickschema` (and load in Brick with vanilla RDFlib)... but let me tell you it's a huge relief to have basic persistence and a (ConjunctiveGraph)[https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.ConjunctiveGraph]... i was starting to feel like I couldn't operationalize Brick in application without it

**Comment by gtfierro** [comment]
It should be possible to have persistent graphs in `brickschema` --- the `brickschema.Graph` it is just a subclass of `rdflib.Graph`, and can accept the `store` argument for one of the persistent implementations. Should also be possible to make a ConjunctiveGraph of `brickschema.Graph` objects as well, but I haven't tested that

**Comment by iamliamc** [comment]
Yeah this is all good... for a while i've been off looking for the right
persistent store that I can host in my cluster... stuff but this postgres
store implementation should be fine for the amount of data i think i'll be
handling

**Comment by iamliamc** [comment]
Yeah the error is what happens if you try to do something on the graph that has been given a store but it hasn't been opened yet... for instance: 

```
    registerplugins()

    SQLALCHEMY_URL = "postgresql+psycopg2://liam:h0tfriend@localhost:5432/spectral_brick"

    store = plugin.get("SQLAlchemy", Store)(identifier="my_store")
    graph = ConjunctiveGraph(store, identifier="my_graph")
    [c for c in graph.contexts()]
```

Produces this error... 
```
Traceback (most recent call last):
  File "/opt/pycharm-2020.3.2/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <listcomp>
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib/graph.py", line 1485, in contexts
    for context in self.store.contexts(triple):
  File "/home/liam/miniconda3/envs/spectral_brick/lib/python3.8/site-packages/rdflib_sqlalchemy/store.py", line 625, in contexts
    with self.engine.connect() as connection:
AttributeError: 'NoneType' object has no attribute 'connect'
```

As soon as I call: 
```
>>> graph.open(SQLALCHEMY_URL, create=True)
1
>>> [c for c in graph.contexts()]
[<Graph identifier=my_graph (<class 'rdflib.graph.Graph'>)>, <Graph identifier=https://brickschema.org/schema/Brick (<class 'rdflib.graph.Graph'>)>]
```

**Comment by gtfierro** [comment]
@iamliamc I know this a bit late, but I am considering the following fix to make brickschema compatible with external stores:

```python
from rdflib import plugin, RDF, Namespace
from rdflib.graph import Graph
from rdflib.store import Store
from rdflib_sqlalchemy import registerplugins

from brickschema import Graph as bGraph

registerplugins()

SQLALCHEMY_URL ="sqlite://"

store = plugin.get("SQLAlchemy", Store)(identifier="my_store")
graph = bGraph(store, identifier="my_graph", postpone_init=True) # <--- the important new kwarg
graph.open(SQLALCHEMY_URL, create=True)
BRICK = Namespace("https://brickschema.org/schema/Brick#")
graph.bind("brick", BRICK)
BLDG = Namespace("https://topology.sbp.spectral.energy/test#")
graph.add((BLDG.Building, RDF.type, BRICK.Building))

result = graph.query("select * where {?s ?p ?o} limit 10")

for subject, predicate, object_ in result:
    print(subject, predicate, object_)

graph.close()
```

Including `postpone_init=True` will delay the internal initialization that `brickschema.Graph` does until *after* the store is opened (if you use `open()` to do so, it will automatically initialize the graph after the store is open). This change will likely arrive with https://github.com/BrickSchema/py-brickschema/pull/64 and be part of the `0.5.0` release of this package. This also incorporates the operator overloading that RDFlib provides so you can do things like add and subtract graphs

**Comment by iamliamc** [comment]
Nice one thanks @gtfierro !
