### ISSUE TITLE
Make use of Docker package optional

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/py-brickschema#5]
Right now only the `OWLRLAllegroInference` class requires it, so we should make it an optional dependency.

**Comment by xyzisinus** [comment]
Thanks for putting docker dependency into README quickly, Gabe.  Things to consider:
* We really need to run AllegroGraph in a container?  The following questions assume the answer is yes.
* The different packages mentioned in README are alternative packages?  If possible, I'd like to see one package with different ways to configure.
* When killing a docker container, it should be pruned.  Or the leftover images jam the disk space.

**Comment by gtfierro** [comment]
> We really need to run AllegroGraph in a container? The following questions assume the answer is yes.

No, but its drastically easier to manage.

> The different packages mentioned in README are alternative packages? If possible, I'd like to see one package with different ways to configure.
No, they are the same package with installation options called "extras" in Python parlance. This is standard practice

> When killing a docker container, it should be pruned. Or the leftover images jam the disk space.

The container is stopped and removed at the end of the reasoning process. If we pruned the image then you would have to redownload it every time you executed the reasoner. Its much more reasonable to not prune the image
The docker container should

**Comment by gtfierro** [comment]
@xyzisinus are your fears assuaged? Check out the new README on this repo

**Comment by xyzisinus** [comment]
> @xyzisinus are your fears assuaged? Check out the new README on this repo
Thank you for the nice work.  i'm running tests now without docker :)  In the README, three packages are listed.  Are they parallel alternatives (one need to install one of them) or brickschema[allegro] and brickschema[reasonable] are additional packages on top of brickschema?

**Comment by gtfierro** [comment]
Like I said above, they're "extras" (see [pip docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies). Its the same package, it just has installation options
