### ISSUE TITLE
Overload operators for Graph

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/py-brickschema#54]
**Steps to reproduce**:
```python
from brickschema import Graph

g = Graph()
g.parse("set.ttl", format="ttl")

h = Graph()
h.parse("subset.ttl", format="ttl")

g = g - h

g.expand("owlrl")
```

> Traceback (most recent call last):
>   File "test_operators.py", line 11, in <module>
> AttributeError: 'Graph' object has no attribute 'expand'

Although the inplace operations (`+=`/`-=`) work without any issues, users might do operations like:
 `a = b + c` (and expect to get the same return type as b and c, like instances of the parent class `rdflib.Graph` do)

**Comment by shreyasnagare** [comment]
https://github.com/RDFLib/rdflib/pull/1349 should address this. If it is rejected, we might have to copy and paste about 30 lines of code from `rdflib.Graph` (without any modifications 😂).

**Comment by shreyasnagare** [comment]
https://github.com/RDFLib/rdflib/pull/1349 should address this. Worst case: copy 30+ lines of code without any modifications from `rdflib.Graph`.

**Comment by gtfierro** [comment]
Thanks for looking into this! I've asked on the PR thread when the next release of rdflib is so that we can incorporate the changes here

**Comment by gtfierro** [comment]
[RDFlib 6.0.0](https://pypi.org/project/rdflib/) was released recently! I'll look into updating brickschema to use the newer package soon; we should include a test that verifies the behavior above works as expected
