### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cbupp** [BrickSchema/py-brickschema#55]
This looks like an interesting repo.

Can you add a license? Or can I have explicit permission to use this?

Thanks!

**Comment by jli113** [comment]
According to their doc, it is using BSD 3-Clause license.

**Comment by epaulson** [comment]
@gtfierro @shreyasnagare any objection to adding a LICENSE file?

**Comment by gtfierro** [comment]
So sorry I didn't have a LICENSE file on this! It is definitely BSD 3-Clause; I"ll add this soon

**Comment by gtfierro** [comment]
Added in #60 ; sorry for the oversight!
