### ISSUE TITLE
brick_validate fails on Building_Meter 

### ISSUE THREAD

**Issue by AsadAliDD** [BrickSchema/py-brickschema#58]
**Command:** 
`brick_validate building_meter.tll`

**Output:**
Validation Report
Conforms: False
Results (3):
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class unit:Unit ; sh:message Literal("Property hasUnit has object with incorrect type") ; sh:path brick:hasUnit ]
	Focus Node: bldg:building_peak_demand
	Value Node: unit:KiloW
	Result Path: brick:hasUnit
	Message: Property hasUnit has object with incorrect type
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class unit:Unit ; sh:message Literal("Property hasUnit has object with incorrect type") ; sh:path brick:hasUnit ]
	Focus Node: bldg:building_energy_sensor
	Value Node: unit:KiloW-HR
	Result Path: brick:hasUnit
	Message: Property hasUnit has object with incorrect type
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
	Severity: sh:Violation
	Source Shape: [ sh:class unit:Unit ; sh:message Literal("Property hasUnit has object with incorrect type") ; sh:path brick:hasUnit ]
	Focus Node: bldg:building_power_sensor
	Value Node: unit:KiloW
	Result Path: brick:hasUnit
	Message: Property hasUnit has object with incorrect type

Additional info (3 constraint violations with offender hint):

Constraint violation:
[] a sh:ValidationResult ;
    sh:focusNode bldg:building_power_sensor ;
    sh:resultMessage "Property hasUnit has object with incorrect type" ;
    sh:resultPath brick:hasUnit ;
    sh:resultSeverity sh:Violation ;
    sh:sourceConstraintComponent sh:ClassConstraintComponent ;
    sh:sourceShape [ sh:class unit:Unit ;
            sh:message "Property hasUnit has object with incorrect type" ;
            sh:path brick:hasUnit ] ;
    sh:value unit:KiloW .
Offending triple:
bldg:building_power_sensor brick:hasUnit unit:KiloW .

Constraint violation:
[] a sh:ValidationResult ;
    sh:focusNode bldg:building_energy_sensor ;
    sh:resultMessage "Property hasUnit has object with incorrect type" ;
    sh:resultPath brick:hasUnit ;
    sh:resultSeverity sh:Violation ;
    sh:sourceConstraintComponent sh:ClassConstraintComponent ;
    sh:sourceShape [ sh:class unit:Unit ;
            sh:message "Property hasUnit has is:issue is:open object with incorrect type" ;
            sh:path brick:hasUnit ] ;
    sh:value unit:KiloW-HR .
Offending triple:
bldg:building_energy_sensor brick:hasUnit unit:KiloW-HR .

Constraint violation:
[] a sh:ValidationResult ;
    sh:focusNode bldg:building_peak_demand ;
    sh:resultMessage "Property hasUnit has object with incorrect type" ;
    sh:resultPath brick:hasUnit ;
    sh:resultSeverity sh:Violation ;
    sh:sourceConstraintComponent sh:ClassConstraintComponent ;
    sh:sourceShape [ sh:class unit:Unit ;
            sh:message "Property hasUnit has object with incorrect type" ;
            sh:path brick:hasUnit ] ;
    sh:value unit:KiloW .
Offending triple:
bldg:building_peak_demand brick:hasUnit unit:KiloW .

**Brick_validate fails for everything with hasUnit property**

**Comment by gtfierro** [comment]
Hi @AsadAliDD ; thanks for letting us know about this issue. Can you share the model (or a minimally reproducing version) that results in this failure?

My initial thought is that the model is missing the statements that assert the `unit:KiloW` to actually be a `unit:Unit`. These statements are contained in the Brick ontology, but the `brick_validate` tool does not automatically import the Brick ontology into the graph when doing the validation.

If you download a recent copy of `Brick.ttl` (e.g. from [here](https://github.com/BrickSchema/Brick/releases/tag/nightly), then you can try the following: `brick_validate -e Brick.ttl building_meter.ttl` which should work.

We should probably add an automatic import of the Brick ontology to the command line validation tool...

**Comment by gtfierro** [comment]
@AsadAliDD I noticed the file you were using (it's one of our own example! How convenient :) ) and I think I have a fix for it. https://github.com/BrickSchema/Brick/pull/299 will address the changes in Brick.ttl that will lead the file to validate correctly

**Comment by AsadAliDD** [comment]
@gtfierro Thanks for the quick fix.

**Comment by gtfierro** [comment]
Of course! Sorry it wasn't in a working state before!

The Brick PR is merged; after the nightly build finishes by tomorrow, you should be able to get the validation working using the following command from the root of the Brick repo:

```
brick_validate -e Brick.ttl examples/building_meter/building_meter.ttl
```

Let me know if that works for you!
