### ISSUE TITLE
Brickify help usage and operations

### ISSUE THREAD

**Issue by Pythonwuerger** [BrickSchema/py-brickschema#70]
Hello this is Philip H. from the Google Group

I looked through the Brickify documentation and I need to reach out for help. 

The first thing I have trouble with are the handlers and operations.
I get that there are different handlers that can be used, but do I understand right that I have to crate the operator myself? 

I understand the basic way the operator is built for the example, but I fail to decipher the deeper logic behind it to be able to apply it to a vastly different data set. Even worse, the logic my data set has is even harder for me to understand and it doesn't have useful column names like the example. Instead it looks like this:

[ahu1 only.csv](https://github.com/BrickSchema/py-brickschema/files/7161749/ahu1.only.csv)

This is the data, I can see the most logic in it.
It would be nice to use the other two as well, but they seem even harder to decode.

[Example.xlsx](https://github.com/BrickSchema/py-brickschema/files/7161734/Example.xlsx)
[Example2.xlsx](https://github.com/BrickSchema/py-brickschema/files/7161737/Example2.xlsx)

Coding an operator seems to prove very difficult. Are there any prebuilt operators that could be used a base? 
If I split the date by delimiters would it be easier to write an operator? 
Is there is more info or a tutorial available. For example why is there the data operation twice in the template?

Also, what handler would be recommended for these formats?
I was told the structure of the first data set should be aligned with the haystack format, but I wan't able to confirm it as of yet. How do I convert it to a haystack turtle so that I can load with the haystack handler?

About the command:
brickify sheet.tsv --output bldg.ttl --input-type tsv --config template.yml

When running it with other data and template than the examples I get an error: 

"'charmap' codec can't decode byte 0x81 in position 462" What does this error message mean?

EDIT: 
The example sheet in the documentation seems to be already normalized data. It seems I need to go back one step.
Since the documentation mentions that it's a job for a technical support team, is it feasible as a one man job? What would you think how long it would take to normalize the data and write a full operator?
I noticed that the first data looks a bit similar to the test data Gabe used in his OpenRefine + BrickBuilder video. What is the best way to make this data compatible with Brickify?

I would be very thankful for any help.

**Comment by gtfierro** [comment]
@shreyasnagare can you take a look at this?

**Comment by shreyasnagare** [comment]
What’s happening?:
Consider the following table: 

| object-name | object-tag-text |
|-------------|-----------------|
| B1          | Hchy            |
| B1’A        | Hchy            |

When you write an operation like:
```yml

operations:
  -
    description: "Adding tag-texts"
    data: |-
      bldg:{object-name} <internal-association-predicate> bldg:{object-tag-text} .

```

brickify tries to create an URI from `bldg:{object-name}`, which ends up looking like `bldg:B1’A` for the second row. The problem here is that the single quote is not URL-safe. If you know the list of unsafe characters in the entire dataset, you could go ahead and use

If you already know what unsafe characters the headers/values might have, you can use the `replace_dict` config ([example](https://github.com/BrickSchema/py-brickschema/blob/6cafa564102be81da72ce2ea3b2ecd36097052b1/brickschema/brickify/src/handlers/Handler/RACHandler/conversions/rac.yml#L252)) to let brickify handle the regex string replacements.

**The safer approach**:
@Pythonwuerger If you don’t know all the characters that might cause problems during serialization, a better idea would be to url-encode all the cells before using brickify. You can use `urllib.parse.quote_plus` or `urllib.parse.quote` for this. 

Also, I see that the last few column headers have the value “null”. If you wish to access that detail from any of the rows, you might wanna rename the headers. 

I’m planning to add that option (auto url-encode) as part of the config sometime next week. Until then, you can try and see if urllib works for you.

**Comment by Pythonwuerger** [comment]
What's happening? : ... well I'm not sure myself to be honest.
Thanks for explaining that error. I'll refrain from using unsafe characters.
There are further Issues for me:

How come the operations from your example link are built different than the the ones in the documentation?

example

```
data: |-
      bldg:{Device and Equipment Name} a brick:VAV .
```

vs

documentation

```
data: |-
      bldg:{VAV name}_0 rdf:type brick:VAV 
```
Which format works or is better? Are they inter-exchangeable? What does the "bldg:" and the "_0" do?

I tried to manually change the table format so something like this:

| Building Name | AHU name |Energy Recovery |Pump | Command|
| ------------- | ------------- |------------- |------------- |-------------|
| B1                 | AHU1           |AHU1_Erc      | AHU1_PU |AHU1_Cmd |

Or should I keep more of the tree format? Ex. B1_AHU1_PU

So if I would want to add the AHU from my files could I do it like this?:
The AHU also has a lot of parts, such as a Pump for energy recovery commands (It has many other commands and pumps as well, so I think the upper setup might be too ambiguous, so perhaps should I keep the tree format Ex. B1_AHU1_Erc_PU) 

```

operations:
  -
  description: "adding building"
    data: |-
     bldg:{Building Name}_0 rdf:type brick:Building.
  
 -
  description: "adding AHU"
    data: |-
     bldg:{AHU name}_0 rdf:type brick:AHU.
  
 -
  description: "adding Erc"
    data: |-
     bldg:{Energy Recovery}_0 rdf:type brick:("can't find a fitting one").
  
 -
  description: "adding Pump"
    data: |-
     bldg:{Pump}_0 rdf:type brick:Pump.

 -
   description: "adding Command"
    data: |-
     bldg:{Command}_0 rdf:type brick:Command.

```

Now of course these relationships aren't mapped right?
I don't see any mapping in the example, in the documentation however I find: 

 ```
- template: |-
      {{ num_triples(value['VAV name'], "brick:hasPoint", value['temperature sensor'], value['sensors'], "brick:Temperature_Sensor") }}

  - template: |-
      {{ num_triples(value['VAV name'], "brick:hasPoint", value['temperature setpoint'], value['setpoints'], "brick:Temperature_Setpoint") }}

macros:
  - |-
    {% macro num_triples(subject, predicate, name, num, type) %}
        {% for i in range(num) %}
          bldg:{{ name }}_{{ i }} a {{ type }} .
          bldg:{{ subject }} {{ predicate }} bldg:{{ name }}_{{ i }} .
        {% endfor %}
    {% endmacro %}
```

I'm not sure how this would be used to link these parts together. Even harder there are many many more like a ventilators, preheaters, vales,  all part of different subparts of the AHU with their own settings, sensors and commands.

If my understanding is correct I think the relationships of the simplified exert should be : 
B1 has equipment AHU1 has part Erc has part Pump has point Command
Please correct me, if i misunderstood something. 
How would the template and Macros needed to be built, to correctly map the relationships?

**Comment by Pythonwuerger** [comment]
As it turned out, it is possible to operate an entire object-name (e.g. B1'A'Ahu1'FanSu'Mdlt) as an instance. With the help of conditions the keys can be assigned to specific bricks depending on how the object-name ends. For a lot of notations of my datasets it is first necessary to find out which Brick fits best, or even to define additional ones.
